flags: {}

extra-package-dbs: []


packages:
- '.'
- location:
    git: https://github.com/runeksvendsen/bitcoin-payment-channel.git
    commit: ba596c2d9e616d3bdbb041e2d9cb792f1e6faef9
  extra-dep: true
- location:
    git: https://github.com/runeksvendsen/haskell-bitcoin-api.git
    commit: d3de7f41a68a1050e02fcb7f7cbf90c4979c02a4
  extra-dep: true

flags:
    snap-server:
        openssl: true

extra-deps:
- haskoin-core-0.3.0
- snap-server-0.9.5.1
# - bitcoin-payment-channel-0.1.1.0
- murmur3-1.0.1
- pbkdf-1.1.1.1
- secp256k1-0.4.5
- text-1.2.2.0
- JsonGrammar-1.0.4
- language-typescript-0.0.4
- stack-prism-0.1.5
- snap-cors-1.2.9

resolver: lts-5.2
