resolver: lts-6.4

flags: {}

extra-package-dbs: []


packages:
- '.'
- location:
    git: https://github.com/runeksvendsen/bitcoin-payment-channel.git
    commit: a1630fc3d45140510f4fb6361976a1e7f0421069
  extra-dep: true
- location:
    git: https://github.com/runeksvendsen/haskell-bitcoin-api.git
    commit: 7ff62829fb4891ce2f7aeb88ac40ef02b69f37f3
  extra-dep: true
## APISpec.Blockchain:
- location:
    git: https://github.com/runeksvendsen/blockchain-restful-address-index.git
    commit: f627f1699405e13ac3bf31fcea23f4f4c14440cd
  extra-dep: true
- location:
    git: https://github.com/runeksvendsen/haskell-stm-diskmap.git
    commit: 12f4749810424da84e8d1f0f1da506a9edebbb93
  extra-dep: true

#flags:
#    snap-server:
#        openssl: true

extra-deps:
# Haskoin
- haskoin-core-0.3.1
- murmur3-1.0.2
- pbkdf-1.1.1.1
- secp256k1-0.4.6
# Snap
- snap-1.0.0.0
- snap-core-1.0.0.0
- snap-server-1.0.0.0
- heist-1.0.0.0
- xmlhtml-0.2.3.5
- io-streams-haproxy-1.0.0.0
# _Other
- spawn-0.3



