flags: {}

extra-package-dbs: []

flags:
    snap-server:
        openssl: true

extra-deps:
- haskoin-core-0.3.0
- snap-server-0.9.5.1
- bitcoin-payment-channel-0.1.1.0
- murmur3-1.0.1
- pbkdf-1.1.1.1
- secp256k1-0.4.5
- text-1.2.2.0
- JsonGrammar-1.0.4
- language-typescript-0.0.4
- stack-prism-0.1.5
- snap-cors-1.2.9

resolver: lts-5.2
