resolver: lts-6.4

flags: {}

extra-package-dbs: []


packages:
- '.'
- location:
    git: https://github.com/runeksvendsen/bitcoin-payment-channel.git
    commit: ed3092f7fab790b4c17f035baa98b34be9b5b71e
  extra-dep: true
- location:
    git: https://github.com/runeksvendsen/haskell-bitcoin-api.git
    commit: 41747640f0ee964db2ca2edefc3420a4cf201b33
  extra-dep: true
## APISpec.Blockchain:
- location:
    git: https://github.com/runeksvendsen/blockchain-restful-address-index.git
    commit: 1aca098c0a26fe4c39d9901199696c648b2987c0
  extra-dep: true
- location:
    git: https://github.com/runeksvendsen/haskell-stm-diskmap.git
    commit: 7847d77d2574337969e61acd6d8cf1091ba77fb2
  extra-dep: true
#- location:
#    git: https://github.com/haskell-servant/servant.git
#    commit: 040db21152ebe0da106e08550e7c11983453918a
#  extra-dep: true
#  subdirs:
#    - servant
#    - servant-client
#    - servant-server

#flags:
#    snap-server:
#        openssl: true

extra-deps:
# Haskoin
- haskoin-core-0.4.0
- murmur3-1.0.3
- pbkdf-1.1.1.1
- secp256k1-0.4.6
# Snap
- snap-1.0.0.0
- snap-core-1.0.0.0
- snap-server-1.0.0.0
- heist-1.0.0.0
- xmlhtml-0.2.3.5
- io-streams-haproxy-1.0.0.0
# _Other
- spawn-0.3



