resolver: lts-7.1

flags: {}

extra-package-dbs: []


packages:
- '.'
#- '/Users/rune/IdeaProjects/bitcoin-payment-channel'
- location:
    git: https://github.com/runeksvendsen/bitcoin-payment-channel.git
    commit: b6141d7d369b14aca6fcc3705aed34a68afa0001
  extra-dep: true
- location:
    git: https://github.com/runeksvendsen/haskell-rbpcp-api.git
    commit: caa0a5db6ea7d45df1e2e858193ec6d904f22adc
  extra-dep: true
- location:
    git: https://github.com/runeksvendsen/haskell-bitcoin-api.git
    commit: 41747640f0ee964db2ca2edefc3420a4cf201b33
  extra-dep: true
## APISpec.Blockchain:
- location:
    git: https://github.com/runeksvendsen/blockchain-restful-address-index.git
    commit: 1aca098c0a26fe4c39d9901199696c648b2987c0
  extra-dep: true
- location:
    git: https://github.com/runeksvendsen/haskell-stm-diskmap.git
    commit: 5900c915faa2efa40511f1f0bce7c1826857baa0
  extra-dep: true


extra-deps:
# Haskoin
- haskoin-core-0.4.0
- murmur3-1.0.3
- pbkdf-1.1.1.1
- secp256k1-0.4.6
# Snap
- snap-1.0.0.0
- snap-core-1.0.0.0
- snap-server-1.0.0.0
- heist-1.0.0.0
- xmlhtml-0.2.3.5
- io-streams-haproxy-1.0.0.0
# _Other
- spawn-0.3
- map-syntax-0.2.0.1
- cereal-text-0.1.0.2



