flags: {}

extra-package-dbs: []

packages:
- '.'
- location:
    git: https://github.com/haskoin/haskoin.git
    commit: 3929cc64ff2ae2c1714720b00d7205b6451708c6
  subdirs:
  - haskoin-core
  extra-dep: true


flags:
    snap-server:
        openssl: true

extra-deps:
- snap-server-0.9.5.1
- bitcoin-payment-channel-0.1.1.0
- murmur3-1.0.1
- pbkdf-1.1.1.1
- secp256k1-0.4.5
- text-1.2.2.0
- JsonGrammar-1.0.4
- language-typescript-0.0.4
- stack-prism-0.1.5
- snap-cors-1.2.9

resolver: lts-5.2
