stanzas:
    - type: webapp
      exec: ../PayChanServer
      args:
        - "--environment=/home/rune/paychan/live"
      host: paychan.runeks.me
      ssl:
        key: server.key
        certificate: runeks-rapid.pem
        chain-certificates: []

