stanzas:
    - type: webapp
      exec: ../PayChanServer
      args:
        - /home/rune/code/restful-payment-channel-server/config/live/config/server.cfg
      host: paychan.runeks.me
      ssl:
        key: /opt/keter/etc/server.key
        certificate: /opt/keter/etc/runeks-rapid.pem
        chain-certificates: []
    - type: background
      exec: ../ChanStore
      args:
        - /home/rune/code/restful-payment-channel-server/config/live/config/store.cfg
      restart-count: 999
      restart-delay-seconds: 1
    - type: background
      exec: ../SigningService
      restart-count: 0
      args:
        - /home/rune/code/restful-payment-channel-server/config/live/config/signing.cfg
