stanzas:
    - type: webapp
      exec: ../PayChanServer
      args:
        - "--environment=/home/rune/paychan/live"
      host: paychan.runeks.me
      ssl:
        key: /opt/keter/etc/server.key
        certificate: /opt/keter/etc/runeks-rapid.pem
        chain-certificates: []

