stanzas:
    - type: webapp
      exec: ../PayChanServer
      args:
        - /home/rune/code/restful-payment-channel-server/config/debug/config/server.cfg
      host: paychantest.runeks.me
      ssl:
        key: /opt/keter/etc/testpay.key
        certificate: /opt/keter/etc/testpay.pem
        chain-certificates:
          - /opt/keter/etc/comodo.pem
    - type: background
      exec: ../ChanStore
      args:
        - /home/rune/code/restful-payment-channel-server/config/debug/config/store.cfg
      restart-count: 999999999
      restart-delay-seconds: 5
  - type: background
      exec: ../SigningService
      args:
        - /home/rune/code/restful-payment-channel-server/config/debug/config/signing.cfg


